name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build package
        run: |
          yarn install --silent
          yarn run build

      - uses: actions/upload-artifact@main
        if: matrix.node-version == '14.x'
        with:
          name: build artifacts
          path: dist/

  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: actions/download-artifact@main
        with:
          name: build artifacts
          path: dist

      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version

      - run: npm pack

      - uses: actions/upload-artifact@main
        with:
          name: package artifacts
          path: "*.tgz"

  publish:
    name: "Publish to GitHub Packages"
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - uses: actions/download-artifact@main
        with:
          name: package artifacts

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@ablause"

      - run: echo "registry=https://npm.pkg.github.com/@ablause" >> .npmrc

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish package
        run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
