name: Create and publish a package

on:
  release:
    types: [created]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install and build package
        run: |
          yarn install
          yarn run build

      - uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: dist/

  push-image:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@main
        with:
          name: build artifacts
          path: dist

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://npm.pkg.github.com

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
