on: [push, pull_request]
name: Build, Test and maybe Publish
env:
  NPM_REGISTRY_URL: "https://npm.pkg.github.com/"

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install & Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Test
        run: yarn test

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@ablause"

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
